# Generated by Django 3.0.7 on 2020-06-27 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 6, 27, 12, 50, 59, 420970))),
            ],
        ),
    ]
